
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log debug;
pid        /run/nginx.pid;


events {
    worker_connections  16;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    

    upstream backend_cluster {
        server app_craftplace:8080 weight=2;  # Основной (запись + чтение)
        server app_craftplace_replica1:8081 weight=1; # Реплика 1 (только чтение)
        server app_craftplace_replica2:8082 weight=1; # Реплика 2 (только чтение)
    }

    upstream backend_primary {
        server app_craftplace:8080;
    }

    upstream backend_mirror {
        server app_craftplace_mirror:8083;
    }

    # Подтверждение работы в Response Headers - content-encoding gzip
    gzip on;
    gzip_vary on;               # Добавляет заголовок
    gzip_min_length 1024;       # Сжимает только файлы больше 1024 б
    # gzip_proxied any;         # Cжимать все проксируемые ответы, чтобы сжатие работало и для контента от приложения, а не только для статики.
    gzip_comp_level 6;          # Уровень сжатия (1-9)
    gzip_types
        text/plain
        text/css
        text/xml
        text/javascript
        application/javascript
        application/xml+rss
        application/json
        image/svg+xml;
    gzip_disable "msie6";       # Отключает сжатие для Internet Explorer 6 - имеет баги с обработкой gzip-контента

    # Подтверждение работы в Response Headers - x-cache-status MISS/HIT
    # proxy_cache_key "$scheme$request_method$host$request_uri";            # проткол, метод запроса, доменное имя, полный URI
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:10m     # выделяем 10 МБ для хранения ключей кэша
                     max_size=1g inactive=60m use_temp_path=off;            # общий размер кэша - 1g, неиспользуемые данные удаляются через 60 минут
    proxy_cache_valid 200 302 10m;                                          # Успешные ответы - 10 минут
    proxy_cache_valid 404 1m;                                               # 404 ошибки - 1 минута
    proxy_cache_valid any 5s;                                               # Остальное - 5 секунд

    # log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                   '$status $body_bytes_sent "$http_referer" '
    #                   '"$http_user_agent" "$http_x_forwarded_for"'
    #                   '"$upstream_cache_status"';
    log_format debug_proxy '$remote_addr - $remote_user [$time_local] '
                           '"$request" $status $body_bytes_sent '
                           '"$http_referer" "$http_user_agent" '
                           'proxy_to: "$upstream_addr" '
                           'proxy_status: "$upstream_status" '
                           'req_time: $request_time '
                           'upstream_time: $upstream_response_time'
                           'cache_status: $upstream_cache_status';

    access_log  /var/log/nginx/access.log  debug_proxy;

    sendfile        on;
    #tcp_nopush     on;
    keepalive_timeout  65;
    include /etc/nginx/conf.d/*.conf;
}
