

server {
    listen 80;
    server_name localhost;

    # Обслуживаем Swagger UI полностью из статики
    location /swagger/ {
        proxy_pass http://app_craftplace:8080/swagger/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

  


    # Главная страница
    location / {
        root /usr/share/nginx/static;
        index index.html; 
        try_files $uri $uri/ /index.html;
    }

    # API routes
    location /api/v1/ {
        proxy_pass http://app_craftplace:8080/api/v1/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 30s;
        proxy_read_timeout 30s;
    }
    # location /swagger/ {
    #     proxy_pass http://app_craftplace:8080/swagger/;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    #     proxy_set_header X-Forwarded-Host $host;
    #     proxy_set_header X-Forwarded-Server $host;
    #     proxy_connect_timeout 30s;
    #     proxy_read_timeout 30s;
        
    #     # Для корректной работы Swagger UI
    #     proxy_redirect off;
    # }

    # # API routes - проксируем к Go-приложению
    # location /api/ {
    #     proxy_pass http://app_craftplace:8080/;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
        
    #     # Для Swagger внутри API
    #     # location /api/swagger/index.html {
    #     #     proxy_pass http://app_craftplace:8080/swagger/index.html;
    #     # }
    # }

    # # Legacy interface
    # location /legacy {
    #     # Если есть legacy приложение - проксируем
    #     # Если нет - отдаем статическую страницу
    #     root /usr/share/nginx/html;
    #     try_files /legacy.html /index.html;
    # }

    # # Documentation - README.md
    # location /documentation {
    #     # Можно отдать raw markdown или сгенерировать HTML
    #     alias /usr/share/nginx/html/README.md;
    #     default_type text/markdown;
    # }


    # # Status page
    # location /status {
    #     stub_status on;
    #     access_log off;
    #     allow all; # В продакшене ограничьте доступ!
    # }

    # # Reserved path - дублирует главную
    # location /reserved/ {
    #     rewrite ^/reserved/(.*)$ /$1 break;
    #     root /usr/share/nginx/html;
    #     try_files $uri $uri/ /index.html;
    # }

    # # Management page
    # location /management {
    #     root /usr/share/nginx/html;
    #     try_files /management.html /index.html;
    # }
}
