server:
  http_listen_port: 9080    
  grpc_listen_port: 0      

positions:
  filename: /tmp/positions.yaml  

clients:
  - url: http://loki_craftplace:3100/loki/api/v1/push  

scrape_configs:
  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
          
    relabel_configs:
      - source_labels: ['__meta_docker_container_label_logging_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_logging_instance']
        target_label: 'instance'
      - source_labels: ['__meta_docker_container_label_logging_environment'] 
        target_label: 'environment'
      - source_labels: ['__meta_docker_container_label_logging_app']
        target_label: 'app'
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      - action: labeldrop
        regex: '__meta_docker_container_label_.*'
      - action: labelkeep
        regex: '(container|service|environment|app|instance|job|filename)'

    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
            service: service
            # env: env
            version: version
            request_id: request_id
            method: method
            path: path
            ip: ip
            user_agent: user_agent
            status: status
            duration: duration
            duration_human: duration_human
            bytes: bytes
            error: error
            # component: component
            # log_type: log_type

      - labels:
          level:     
          service:   

      - timestamp:
          source: time
          format: RFC3339Nano

      - output:
          source: msg
