[build]
cmd = "swag init -g ./cmd/dev/main.go --output ./docs && go build -o ./tmp/main ./cmd/dev/main.go"
bin = "tmp/main"
include_ext = ["go", "yaml", "yml", "env", "tpl", "tmpl", "templ", "html", "css"]
exclude_dir = ["vendor", "tmp", "docs"]
exclude_regex = [".*_templ.go"]
